### ISSUE TITLE
Kotlin version

### ISSUE THREAD

**Issue by ch8n** [BracketCove/AndroidCleanGuiArchitecture#1]
Hi @BracketCove , I'm interested in implementing a kotlin version of the same, please do create a kotlin branch for the same so I can share a PR.

**Comment by BracketCove** [comment]
Sounds good, let's do it!

New branch created here:
https://github.com/BracketCove/AndroidCleanGuiArchitecture/tree/kotlin

**Comment by ch8n** [comment]
Hi @BracketCove done done please do the code review! from here => #2

**Comment by BracketCove** [comment]
All set; thanks for the contribution @ch8n!
